# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - cartesian_robot_slider_controller

  cartesian_robot_slider_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - prismatic_joint_1
      - prismatic_joint_2
      - prismatic_joint_3
    action_ns: follow_joint_trajectory
    default: true