# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    cartesian_robot_slider_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

cartesian_robot_slider_controller:
  ros__parameters:
    joints:
      - prismatic_joint_1
      - prismatic_joint_2
      - prismatic_joint_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity