<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="cartesian_robot">

  <material name="blue">
    <color rgba="0 0 1 1" />
  </material>

  <material name="red">
    <color rgba="1 0 0 1" />
  </material>

  <material name="green">
    <color rgba="0 1 0 1" />
  </material>

  <link name="base_link" />

  <xacro:property name="z_offset" value="1.0" />
  <xacro:property name="l1" value="4.0" />
  <xacro:property name="l2" value="2.4" />
  <xacro:property name="l3" value="0.8" />
  <xacro:property name="l4" value="0.2" />
  <xacro:property name="width" value="0.2" />
  <xacro:property name="holder_offset" value="${z_offset + 0.5}"/>

  <link name="holder_link">
    <inertial>
      <origin xyz="0 ${-width} 0.5" rpy="0 0 0"/>
      <mass value="1000"/>
      <inertia ixx="1000" ixy="0" ixz="0" iyy="1000" iyz="0" izz="1000"/>
    </inertial>
    <visual>
      <origin xyz="0 ${-width} 0.5" rpy="0 0 0"/>
      <geometry>
        <box size="${holder_offset} ${width} ${holder_offset}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 ${-width} 0.5" rpy="0 0 0"/>
      <geometry>
        <box size="${holder_offset} ${width} ${holder_offset}"/>
      </geometry>
    </collision>
  </link>


  <link name="link1">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${l1} ${width} ${width}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${l1} ${width} ${width}"/>
      </geometry>
    </collision>
  </link>

  <link name="link1_b">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${l1} ${width} ${width}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${l1} ${width} ${width}"/>
      </geometry>
    </collision>
  </link>

  <link name="link2">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="1000" ixy="0" ixz="0" iyy="1000" iyz="0" izz="1000"/>
    </inertial>
    <visual>
      <origin xyz="0 ${l2/2} 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${l2} ${width}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 ${l2/2} 0" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${l2} ${width}"/>
      </geometry>
    </collision>
  </link>

  <link name="link3">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="1000" ixy="0" ixz="0" iyy="1000" iyz="0" izz="1000"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${-l3/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${l3}"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${-l3/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${l3}"/>
      </geometry>
    </collision>
  </link>

  <link name="link4">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${l4} ${l4} ${l4}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${l4} ${l4} ${l4}"/>
      </geometry>
    </collision>
  </link>

   <joint name="fixed_holder_joint" type="fixed">
    <parent link="holder_link"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="fixed_link_1" type="fixed">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${z_offset}" rpy="0 0 0"/>
  </joint>

  <joint name="fixed_link_1_b" type="fixed">
    <parent link="base_link"/>
    <child link="link1_b"/>
    <origin xyz="0 ${l2} ${z_offset}" rpy="0 0 0"/>
  </joint>

  <joint name="prismatic_joint_1" type="prismatic">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="${-l1/2} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0.0" upper="${l1}" effort="10" velocity="2.0"/>
  </joint>

  <joint name="prismatic_joint_2" type="prismatic">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0.0" upper="${l2}" effort="100" velocity="2.0"/>
  </joint>

  <joint name="prismatic_joint_3" type="prismatic">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="${width} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 -1"/>
    <limit lower="0.0" upper="${l3}" effort="100" velocity="2.0"/>
  </joint>

</robot>