<?xml version="1.0"?>
<robot name="scara" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="l2" value="0.45"/>
  <xacro:property name="l2_r" value="0.05"/>
  <xacro:property name="l3" value="0.425"/>
  <xacro:property name="l4" value="0.2"/>
  <xacro:property name="l4_r" value="0.05"/>
  <xacro:property name="l5" value="0.3"/>
  <xacro:property name="gripper_length" value="0.1"/>


  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material>

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>

  <material name="green">
    <color rgba="0 1 0 1"/>
  </material>

<!--links-->
  <link name="base_link"/>

  <link name="link_1">
    <visual>
      <geometry>
        <box size="0.12 0.12 0.05"/>
      </geometry>
      <material name="red"/>
      <origin xyz="0 0 0"/>
    </visual>
    <inertial>
      <mass value="1"/>
      <origin xyz="0 0 0.025"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
  </link>

  <link name="link_2">
    <visual>
      <geometry>
        <cylinder length="${l2}" radius="${l2_r}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 ${l2/2}"/>
    </visual>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 ${l2/2}"/>
      <inertia ixx="0.5" ixy="0" ixz="0" iyy="0.5" iyz="0" izz="0.5"/>
    </inertial>
  </link>

  <link name="link_3">
    <visual>
      <geometry>
        <box size="0.1 0.1 ${l3}"/>
      </geometry>
      <material name="red"/>
      <origin rpy="0 1.571 0" xyz="${l3/2} 0 0"/>
    </visual>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="${l3/2} 0 0"/>
      <inertia ixx="0.5" ixy="0" ixz="0" iyy="0.5" iyz="0" izz="0.5"/>
    </inertial>
  </link>

  <link name="link_4">
    <visual>
      <geometry>
        <cylinder length="${l4}" radius="${l4_r}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 0 0"/>
    </visual>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.5" ixy="0" ixz="0" iyy="0.5" iyz="0" izz="0.5"/>
    </inertial>
  </link>

  <link name="link_5">
    <visual>
      <geometry>
        <box size="0.1 0.1 ${l5}"/>
      </geometry>
      <material name="red"/>
      <origin rpy="0 1.571 0" xyz="${l5/2} 0 0"/>
    </visual>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="${l5/2} 0 0"/>
      <inertia ixx="0.5" ixy="0" ixz="0" iyy="0.5" iyz="0" izz="0.5"/>
    </inertial>
  </link>

  <link name="link_6">
    <inertial>
        <origin xyz="0 0 ${l5/2}" />
        <mass value="1"/>
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${l5/2}" />
        <geometry>
          <box size="0.1 0.1 ${l5}" />
      </geometry>
      <material name="green" />
    </visual>
  </link>

  <link name="gripper_link">
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.08 0.08 ${gripper_length}" />
      </geometry>
      <material name="red"/>
    </visual>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" />
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>
  
<!--Joints-->
  <joint name="fixedjoint_1" type="fixed">
    <parent link="base_link"/>
    <child link="link_1"/>
  </joint>

  <joint name="fixedjoint_2" type="fixed">
    <parent link="link_2"/>
    <child link="link_3"/>
    <origin xyz="0 0 ${l2 - 0.05}"/>
  </joint>

  <joint name="fixedjoint_3" type="fixed">
    <parent link="link_4"/>
    <child link="link_5"/>
    <origin xyz="0 0 ${l4/2}"/>
  </joint>
  
<!--revolut joints-->
  <joint name="revolute_1" type="revolute">
    <parent link="link_1"/>
    <child link="link_2"/>
    <origin xyz="0 0 0.05"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-1.57" upper="1.57" velocity="0.5"/>
    <dynamics damping="0.2" friction="0.1"/>
  </joint>

  <joint name="revolute_2" type="revolute">
    <parent link="link_3"/>
    <child link="link_4"/>
    <origin xyz="${l3} 0 0.05"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-1.57" upper="1.57" velocity="0.5"/>
    <dynamics damping="0.2" friction="0.1"/>
  </joint>

  <joint name="gripper_joint" type="revolute">
    <parent link="link_6"/>
    <child link="gripper_link"/>
    <origin xyz="0 0 ${-gripper_length/2}" />
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-1.57" upper="1.57" velocity="0.5"/>
    <dynamics damping="0.2" friction="0.1"/>
  </joint>

  <!--Prismatic joint-->

  <joint name="prismatic_joint_1" type="prismatic">
    <parent link="link_5" />
    <child link="link_6" />
    <origin xyz="${l5} 0 0" rpy="0 0 0" />
    <axis xyz="0 0 -1" />
    <limit lower="0.0" upper="${l5}" effort="100"  velocity="1.0" />
  </joint>
</robot>
